import type { Metadata } from 'next';
import './globals.css';

import ThemeRegistry from '@/components/ThemeRegistry';
import { SettingsProvider } from '@/contexts/SettingsContext';
import React from 'react';

export const metadata: Metadata = {
  title: 'Advocacia',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang='pt-BR'>
      <SettingsProvider>
        <ThemeRegistry>
          <body>{children}</body>
        </ThemeRegistry>
      </SettingsProvider>
    </html>
  );
}
