import type { Metadata } from "next";
import "./globals.css";

import ThemeRegistry from "@/components/ThemeRegistry";

export const metadata: Metadata = {
  title: "Advocacia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <ThemeRegistry>
        <body>{children}</body>
      </ThemeRegistry>
    </html>
  );
}
